{
  "AgentApply_Real_Name": "Họ và tên",
  "AgentApply_Enter_Account": "Từ 5 -15 kí tự, Phải bắt đầu bằng chữ cái, có thể gồm cả chữ cái và số.",
  "AgentApply_Account": "Tên Đăng Nhập Đại Lý",
  "AgentApply_Password": "Mật Khẩu Đăng Nhập",
  "CompanyDeposit_TransferStep1": "- Nạp tiền qua cổng ATM :",
  "CompanyDeposit_TransferStep2": "Bạn có thể qua cổng ATM gần nhất sau đấy dựa vào thông tin trên thống của 789BET để chuyển khoản .",
  "CompanyDeposit_TransferStep3": "- Gửi tiền tại quầy :",
  "CompanyDeposit_TransferStep4": "Bạn có thể qua trực tiếp ngân hàng thông qua ngân hàng chuyển khoản cho 789BET.",
  "CompanyDeposit_TransferStep5": "Chuyển khoản trực tuyến  :",
  "CompanyDeposit_TransferStep6": "Bạn có thể đăng nhập vào ngân hàng online của mình tiến hành copy thông tin của 789BET để chuyển khoản .",
  "CompanyDeposit_TransferStep7": "Lưu ý : Khi chuyển khoản cho 789BET cần vào trực tiếp hệ thống để lấy thông tin mới nhất,tránh chuyển khoản sai vào ngân hàng đóng sẽ ảnh hưởng tới tốc độ nạp cũng như mất tiền.",
  "Franchisee_Account": "Tên Đăng Nhập Đại Lý",
  "Franchisee_Password": "Mật Khẩu Đăng Nhập",
  "Lobby_BG_Fish": "BG BẮN CÁ",
  "Lobby_FC_Fish": "FC BẮN CÁ",
  "Lobby_Fish_Casino": "BẮN CÁ",
  "Lobby_JDB_Fish": "JDB BẮN CÁ",
  "Lobby_JILI_Fish": "JILI BẮN CÁ",
  "Lobby_KA_Fish": "KA BẮN CÁ",
  "Lobby_MG_Fish": "MG BẮN CÁ",
  "Lobby_NS_Fish": "NS BẮN CÁ",
  "Lobby_More_Game": "THÊM NHIỀU TRÒ CHƠI HƠN",
  "Lobby_RICH88_Fish": "R88 BẮN CÁ",
  "Lobby_FTG_Fish": "FTG BẮN CÁ",
  "Lobby_TP_Fish": "TP BẮN CÁ",
  "Lobby_Enter_Game": "Cược Ngay",
  "Register_Member_Account": "Tên đăng nhập",
  "Register_Account_Rules": "Lớn hơn 5 ký tự,bằng chữ,không thêm các ký tự đặc biệt.",
  "Register_Account_Rules_Input": "Lớn hơn 5 ký tự,bằng chữ,không thêm các ký tự đặc biệt.",
  "Register_Member_Password": "Mật khẩu thành viên",
  "Register_Enter_Password": "Hơn 6 ký tự phải bao gồm chữ cái và số.",
  "Register_Enter_Password_Input": "Hơn 6 ký tự phải bao gồm chữ cái và số.",
  "Register_Confirm_Password": "Xác nhận mật khẩu",
  "Register_Enter_Confirm_Password": "Vui lòng xác nhận lại mật khẩu của bạn.",
  "Register_Enter_Confirm_Password_Input": "Vui lòng xác nhận lại mật khẩu của bạn.",
  "Register_Real_Name": "Họ và tên",
  "Register_Name_Rules": "Họ tên ghi in hoa, không dấu  VD: NGUYEN VAN A",
  "Register_Email": "Địa chỉ Email",
  "Register_Enter_Email": "Điền chính xác để lấy lại mật khẩu khi quên (Bắt Buộc).",
  "Register_Enter_Email_Input": "Điền chính xác để lấy lại mật khẩu khi quên (Bắt Buộc).",
  "Register_Mobile": "Số điện thoại",
  "Register_Enter_Mobile": "Số điện thoại nhập bắt đầu bằng 84, Ví dụ: 84868888789",
  "Register_Enter_Mobile_Input": "Số điện thoại nhập bắt đầu bằng 84, Ví dụ: 84868888789",
  "Register_Enter_Birthday": "Điền đúng ngày sinh để nhận quà sinh nhật VIP",
  "Register_Enter_Birthday_Input": "Điền đúng ngày sinh để nhận quà sinh nhật VIP",
  "Shared_Already_Registered": "Bạn co săn san để tạo một tai khoản?",
  "Shared_App": "TẢI APP",
  "Shared_Partner": "ĐẠI LÝ",
  "Shared_Community": "CỘNG ĐỒNG",
  "Shared_Account": "Tài khoản",
  "Shared_Password": "Mật khẩu",
  "Shared_BetRecord": "Lịch Sử Đặt Cược",
  "Shared_Online_Deposit": "Nạp Tiền",
  "Shared_Online_Withdraw": "Rút Tiền",
  "Shared_Transaction_Record": "Chi Tiết Giao Dịch",
  "Shared_ChangeMoneyPassword": "Đổi Mật Khẩu Rút Tiền",
  "Shared_MemberCenter": "Trung Tâm Hội Viên",
  "Shared_Mobile": "Giao Diện Điện Thoại",
  "Shared_Logout": "Đăng Xuất",
  "Shared_Footer_AboutUs": "Giới thiệu về 789BET",
  "Shared_Footer_AmlPolicy": "Chính Sách AML",
  "Shared_Footer_Rule": "Điều khoản và điều kiện",
  "Shared_Footer_Responsible": "Chơi có trách nhiệm",
  "Shared_Footer_Disclaimer": "Miễn trách nhiệm",
  "Shared_Footer_Privacy": "Quyền riêng tư tại 789BET",
  "Shared_Footer_HowToDeposit": "Hướng dẫn nạp tiền",
  "Shared_Footer_HowWithdrawals": "Hướng dẫn rút tiền",
  "Shared_Footer_FAQ": "Những câu hỏi thường gặp",
  "Shared_Footer_Brand": "Đại sứ thương hiệu",
  "Shared_Footer_ContactUs": "Liên hệ",
  "Shared_Footer_Partner": "Đối tác",
  "Shared_Footer_MobileBet": "Giao Diện Điện Thoại",
  "Shared_Home_News": "TIN TỨC",
  "Shared_Home_Tutorial": "HƯỚNG DẪN",
  "Shared_JoinUs": "Đăng ký tài khoản",
  "Shared_Member_Center": "THÔNG TIN",
  "Shared_Menu": "TỔNG HỢP",
  "Shared_More_Info": "Tìm hiểu thêm",
  "Shared_Nav_Board": "GAME BÀI",
  "Shared_Nav_Casino": "NỔ HŨ",
  "Shared_Nav_CockFighting": "ĐÁ GÀ",
  "Shared_Nav_LiveCasino": "CASINO",
  "Shared_Nav_Lottery": "XỔ SỐ",
  "Shared_Nav_Promotions": "KHUYẾN MÃI",
  "Shared_Nav_Sports": "THỂ THAO",
  "Shared_UnRegistered": "Không có tài khoản?",
  "Shared_Quick_Link": "Liên kết nhanh",
  "Shared_Top_Game": "TOP HỦ TRONG TUẦN",
  "Shared_Play": "Cược Ngay",
  "Shared_Live_Info": "Nhà cung cấp baccarat thời gian thực, Trực tiếp từ Sòng Bạc",
  "Shared_Free_Play": "Chơi Thử Miễn Phí",
  "Shared_NewsInfo": "THÔNG BÁO: ",
  "Shared_Web": "THƯƠNG HIỆU",
  "Common_Enter_Captcha": "Xin vui lòng nhập kết quả mã xác minh",
  "LeaderBoard_Matches": "CƯỢC VÀ GIẢI ĐẤU HÔM NAY"
}