import gameName from "./gameName";

export const dataGame = [
  {
    id: 1,
    name: "PG Điện Tử",
    link: `/games/SlotCasino/${gameName.PG}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/pg.png",
  },
  {
    id: 2,
    name: "JILI Điện Tử",
    link: `/games/SlotCasino/${gameName.Jili}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/jl.png",
  },
  {
    id: 3,
    name: "TP Điện Tử",
    link: `/games/SlotCasino/${gameName.TP}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/tp.png",
  },
  {
    id: 4,
    name: "PP Điện Tử",
    link: `/games/SlotCasino/${gameName.PP}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/pp.png",
  },
  {
    id: 5,
    name: "CQ9 Điện Tử",
    link: `/games/SlotCasino/${gameName.CQ9}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/cq9.png",
  },
  {
    id: 6,
    name: "MG Điện Tử",
    link: `/games/SlotCasino/${gameName.MG}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/mg.png",
  },
  {
    id: 7,
    name: "JDB Điện Tử",
    link: `/games/SlotCasino/${gameName.JDB}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/jd.png",
  },
  {
    id: 8,
    name: "Spribe Điện Tử",
    link: `/games/SlotCasino/${gameName.SPRIBE}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/spribe.png",
  },
  {
    id: 9,
    name: "FC Điện Tử",
    link: `/games/SlotCasino/${gameName.FC}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/fc.png",
  },
  {
    id: 10,
    name: "VA Điện Tử",
    link: `/games/SlotCasino/${gameName.VA}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/va.png",
  },
  {
    id: 11,
    name: "BNG Điện Tử",
    link: `/games/SlotCasino/${gameName.BNG}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/bng.png",
  },
  {
    id: 12,
    name: "KA Điện Tử",
    link: `/games/SlotCasino/${gameName.KA}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ka.png",
  },
  // {
  //   id: 13,
  //   name: "PS Điện Tử",
  //   link: "/games/SlotCasino/PS",
  //   img: ''  // },
  {
    id: 14,
    name: "R88 Điện Tử",
    link: `/games/SlotCasino/${gameName.R88}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/r88.png",
  },
  {
    id: 15,
    name: "PT Điện Tử",
    link: `/games/SlotCasino/${gameName.PT}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/pt.png",
  },
  // {
  //   id: 16,
  //   name: "HB Điện Tử",
  //   link: "/games/SlotCasino/HB",
  //   img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/hb.png",
  // },
  // {
  //   id: 17,
  //   name: "T1 Điện Tử",
  //   link: "/games/SlotCasino/T1",
  //   img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/t1.png",
  // },
  {
    id: 18,
    name: "AFB Điện Tử",
    link: `/games/SlotCasino/${gameName.AFB}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/afb.png",
  },
  {
    id: 19,
    name: "NS Điện Tử",
    link: `/games/SlotCasino/${gameName.NS}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ns.png",
  },
  {
    id: 20,
    name: "NW Điện Tử",
    link: `/games/SlotCasino/${gameName.MW}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/mw.png",
  },
  {
    id: 21,
    name: "Askme Điện Tử",
    link: `/games/SlotCasino/${gameName.ASKME}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/as.png",
  },
  // {
  //   id: 22,
  //   name: "GP Điện Tử",
  //   link: "/games/SlotCasino/GP",
  //   img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/gp.png",
  // },
  {
    id: 24,
    name: "YGR Điện Tử",
    link: `/games/SlotCasino/${gameName.YGR}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ygr.png",
  },
  // {
  //   id: 25,
  //   name: "YB Điện Tử",
  //   code: "yb",
  //   img: "",
  // },
  // {
  //   id: 26,
  //   name: "Askme Điện Tử",
  //   code: "askme",
  //   img: "",
  // },
  // {
  //   id: 27,
  //   name: "RTG Slots",
  //   code: "rtg",
  //   img: "",
  // },
  // {
  //   id: 28,
  //   name: "EvoPlay Điện Tử",
  //   code: "evoplay",
  //   img: "",
  // },
  // {
  //   id: 29,
  //   name: "Live22 Điện Tử",
  //   code: "live22",
  //   img: "",
  // }
];
export const dataGameFish = [
  {
    id: 1,
    name: "JILI Bắn cá",
    link: `/games/FishGame/${gameName.Jili}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/jl.png",
  },
  {
    id: 2,
    name: "TP Bắn cá",
    link: `/games/FishGame/${gameName.TP}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/tp.png",
  },
  {
    id: 3,
    name: "FC Bắn cá",
    link: `/games/FishGame/${gameName.FC}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/fc.png",
  },
  {
    id: 4,
    name: "JDB Bắn cá",
    link: `/games/FishGame/${gameName.JDB}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/jd.png",
  },
  {
    id: 5,
    name: "CQ9 Bắn cá",
    link: `/games/FishGame/${gameName.CQ9}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/cq9.png",
  },
  {
    id: 6,
    name: "BG Bắn cá",
    link: `/games/FishGame/${gameName.BG}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/bg.png",
  },
  {
    id: 7,
    name: "FTG Bắn cá",
    link: `/games/FishGame/${gameName.FTG}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ftg.png",
  },
  {
    id: 8,
    name: "KA Bắn cá",
    link: `/games/FishGame/${gameName.KA}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ka.png",
  },
  {
    id: 9,
    name: "YGR Điện Tử",
    link: `/games/FishGame/${gameName.YGR}`,
    img: "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/games/ygr.png",
  },
];

export const dataGameSlideComponent = [
  {
    id: 15255,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "1",
    gameName: "Honey Trap of Diao Chan",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_1.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:03.725Z",
    createdAt: "2024-11-14T09:59:03.725Z",
  },
  {
    id: 15256,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "2",
    gameName: "Gem Saviour",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_2.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:03.828Z",
    createdAt: "2024-11-14T09:59:03.828Z",
  },
  {
    id: 15257,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "3",
    gameName: "Fortune Gods",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_3.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:03.933Z",
    createdAt: "2024-11-14T09:59:03.933Z",
  },
  {
    id: 15258,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "6",
    gameName: "Medusa 2: The Quest of Perseus",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_6.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.039Z",
    createdAt: "2024-11-14T09:59:04.039Z",
  },
  {
    id: 15259,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "7",
    gameName: "Medusa 1: The Curse of Athena",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_7.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.145Z",
    createdAt: "2024-11-14T09:59:04.145Z",
  },
  {
    id: 15260,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "18",
    gameName: "Hood vs Wolf",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_18.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.253Z",
    createdAt: "2024-11-14T09:59:04.253Z",
  },
  {
    id: 15261,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "20",
    gameName: "Reel Love",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_20.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.360Z",
    createdAt: "2024-11-14T09:59:04.360Z",
  },
  {
    id: 15262,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "24",
    gameName: "Win Win Won",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_24.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.463Z",
    createdAt: "2024-11-14T09:59:04.463Z",
  },
  {
    id: 15263,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "25",
    gameName: "Plushie Frenzy",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_25.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:04.566Z",
    createdAt: "2024-11-14T09:59:04.566Z",
  },
  {
    id: 15264,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "26",
    gameName: "Tree of Fortune",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_26.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:05.771Z",
    createdAt: "2024-11-14T09:59:05.771Z",
  },
  {
    id: 15265,
    partnerName: "fe",
    providerId: "1007",
    providerName: "PG Soft",
    gameTypeId: "1",
    gameTypeName: "SLOT",
    gameId: "28",
    gameName: "Hotpot",
    gameIconUrl:
      "https://cdn.jsdelivr.net/gh/snail5555/akv@main/789bet/images/slider-game/PGSoft_28.png",
    rank: 999,
    rankHot: 999,
    rankNew: 999,
    rankSuper: 999,
    updatedAt: "2024-11-14T09:59:05.875Z",
    createdAt: "2024-11-14T09:59:05.875Z",
  },
];
