export const gameProviders = [
  { gpId: -1, name: "Sbo" },
  { gpId: 0, name: "Wan Mei" },
  { gpId: 2, name: "CQNine" },
  { gpId: 3, name: "Pragmatic Play" },
  { gpId: 5, name: "Big Gaming" },
  { gpId: 7, name: "Sexy Gaming" },
  { gpId: 10, name: "Joker Gaming" },
  { gpId: 11, name: "RealTimeGaming" },
  { gpId: 12, name: "IONLC" },
  { gpId: 13, name: "WorldMatch" },
  { gpId: 14, name: "SBO Slots" },
  { gpId: 16, name: "FunkyGames" },
  { gpId: 19, name: "SaGaming" },
  { gpId: 20, name: "EvolutionGaming" },
  { gpId: 22, name: "Yggdrasil" },
  { gpId: 28, name: "AllBet" },
  { gpId: 29, name: "MicroGaming" },
  { gpId: 30, name: "CQNineLC" },
  { gpId: 33, name: "GreenDragon" },
  { gpId: 35, name: "PGSoft" },
  { gpId: 36, name: "FlowGamingHub" },
  { gpId: 38, name: "PragmaticPlayCasino" },
  { gpId: 39, name: "RedTiger" },
  { gpId: 46, name: "Sv388Cockfighting" },
  { gpId: 47, name: "GiocoPlus" },
  { gpId: 1000, name: "ArcadiaGaming" },
  { gpId: 1009, name: "MPoker" },
  { gpId: 1010, name: "YGR" },
  { gpId: 1011, name: "Digitain" },
  { gpId: 1012, name: "TCGaming" },
  { gpId: 1015, name: "AFBSports" },
  { gpId: 1016, name: "AFBGaming" },
  { gpId: 1019, name: "YeeBet" },
  { gpId: 1020, name: "JiLiGaming" },
  { gpId: 1021, name: "OGLive" },
  { gpId: 1022, name: "BTiSports" },
  { gpId: 1024, name: "AFBCasino" },
  { gpId: 1025, name: "PlayTech Live Casino" },
  { gpId: 1026, name: "Rich88" },
  { gpId: 1027, name: "MicroGaming LiveCasino" },
  { gpId: 1029, name: "568WinGames" },
  { gpId: 1030, name: "DreamGaming" },
  { gpId: 1031, name: "Habanero" },
  { gpId: 1032, name: "RelaxGaming" },
  { gpId: 1033, name: "KingMidas" },
  { gpId: 1034, name: "AdvantPlay" },
  { gpId: 1035, name: "AsiaGaming" },
  { gpId: 1036, name: "Live22" },
  { gpId: 1037, name: "WE Casino" },
  { gpId: 1038, name: "Netent" },
  { gpId: 1039, name: "BigTimeGaming" },
  { gpId: 1040, name: "NoLimitCity" },
  { gpId: 1041, name: "93connect" },
  { gpId: 1042, name: "KAGaming" },
  { gpId: 1043, name: "WCasino" },
  { gpId: 1044, name: "PlayStar" },
  { gpId: 1045, name: "MikiWorld" },
  { gpId: 1046, name: "FaChai" },
  { gpId: 1047, name: "GamePlaySlot" },
  { gpId: 1048, name: "GameplayLiveCasino" },
  { gpId: 1049, name: "GameplayLottery" },
  { gpId: 1050, name: "BoleGaming" },
  { gpId: 1053, name: "PandaSports" },
  { gpId: 1054, name: "LambdaGaming" },
  { gpId: 1055, name: "WGBCockfighting" },
  { gpId: 1056, name: "Phoenix 7" },
  { gpId: 1057, name: "CC88" },
  { gpId: 1058, name: "JDB" },
  { gpId: 1059, name: "ClotPlay" },
  { gpId: 1060, name: "PegasusSlot" },
  { gpId: 1062, name: "DragoonSoft" },
  { gpId: 1064, name: "ViaCasino" },
  { gpId: 1116, name: "Nextspin" },
  { gpId: 1067, name: "Booongo" },
  { gpId: 1068, name: "TomHorn" },
  { gpId: 1070, name: "WS168Cockfighting" },
  { gpId: 1071, name: "5GGaming" },
  { gpId: 1073, name: "Motivation" },
];
